/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedTiposDeLeadRouteImport } from './routes/_authenticated/tipos-de-lead'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedFunilIndexRouteImport } from './routes/_authenticated/funil.index'
import { Route as AuthenticatedFunilFunnelIdRouteImport } from './routes/_authenticated/funil.$funnelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTiposDeLeadRoute =
  AuthenticatedTiposDeLeadRouteImport.update({
    id: '/tipos-de-lead',
    path: '/tipos-de-lead',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilIndexRoute = AuthenticatedFunilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFunilRoute,
} as any)
const AuthenticatedFunilFunnelIdRoute =
  AuthenticatedFunilFunnelIdRouteImport.update({
    id: '/$funnelId',
    path: '/$funnelId',
    getParentRoute: () => AuthenticatedFunilRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/funil': typeof AuthenticatedFunilRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/tipos-de-lead': typeof AuthenticatedTiposDeLeadRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/funil/$funnelId': typeof AuthenticatedFunilFunnelIdRoute
  '/funil/': typeof AuthenticatedFunilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/tipos-de-lead': typeof AuthenticatedTiposDeLeadRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/funil/$funnelId': typeof AuthenticatedFunilFunnelIdRoute
  '/funil': typeof AuthenticatedFunilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/tipos-de-lead': typeof AuthenticatedTiposDeLeadRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/funil/$funnelId': typeof AuthenticatedFunilFunnelIdRoute
  '/_authenticated/funil/': typeof AuthenticatedFunilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/comissoes'
    | '/dashboard'
    | '/formularios'
    | '/funil'
    | '/relatorios'
    | '/tarefas'
    | '/tipos-de-lead'
    | '/usuarios'
    | '/funil/$funnelId'
    | '/funil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/comissoes'
    | '/dashboard'
    | '/formularios'
    | '/relatorios'
    | '/tarefas'
    | '/tipos-de-lead'
    | '/usuarios'
    | '/funil/$funnelId'
    | '/funil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/comissoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/formularios'
    | '/_authenticated/funil'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarefas'
    | '/_authenticated/tipos-de-lead'
    | '/_authenticated/usuarios'
    | '/_authenticated/funil/$funnelId'
    | '/_authenticated/funil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tipos-de-lead': {
      id: '/_authenticated/tipos-de-lead'
      path: '/tipos-de-lead'
      fullPath: '/tipos-de-lead'
      preLoaderRoute: typeof AuthenticatedTiposDeLeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil/': {
      id: '/_authenticated/funil/'
      path: '/'
      fullPath: '/funil/'
      preLoaderRoute: typeof AuthenticatedFunilIndexRouteImport
      parentRoute: typeof AuthenticatedFunilRoute
    }
    '/_authenticated/funil/$funnelId': {
      id: '/_authenticated/funil/$funnelId'
      path: '/$funnelId'
      fullPath: '/funil/$funnelId'
      preLoaderRoute: typeof AuthenticatedFunilFunnelIdRouteImport
      parentRoute: typeof AuthenticatedFunilRoute
    }
  }
}

interface AuthenticatedFunilRouteChildren {
  AuthenticatedFunilFunnelIdRoute: typeof AuthenticatedFunilFunnelIdRoute
  AuthenticatedFunilIndexRoute: typeof AuthenticatedFunilIndexRoute
}

const AuthenticatedFunilRouteChildren: AuthenticatedFunilRouteChildren = {
  AuthenticatedFunilFunnelIdRoute: AuthenticatedFunilFunnelIdRoute,
  AuthenticatedFunilIndexRoute: AuthenticatedFunilIndexRoute,
}

const AuthenticatedFunilRouteWithChildren =
  AuthenticatedFunilRoute._addFileChildren(AuthenticatedFunilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedTiposDeLeadRoute: typeof AuthenticatedTiposDeLeadRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedTiposDeLeadRoute: AuthenticatedTiposDeLeadRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
